### ISSUE TITLE
Doesn't work on Windows 10

### ISSUE THREAD

**Issue by Dingo64** [lainz/FileAssociation#1]
No idea what is wrong but it doesn't work.
with assoc.RegisterForAllUsers:=false; it doesn't even show the message from the example.
With "true" and when run as admin it does show a message but a file (.pdf) is not associated with my program.

**Comment by lainz** [comment]
Hi. Please check the Lazarus wiki about file association. There are other methods you can try.

By default on newer windows only the user can choose the file association. You can only propose the association..
